"""init

Revision ID: 40750a96ae6e
Revises:
Create Date: 2026-04-23 23:37:17.916783

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40750a96ae6e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tilda_jobs_status",
        sa.Column("tilda_jobs_status_id", sa.Integer(), nullable=False),
        sa.Column("status_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("tilda_jobs_status_id", name=op.f("pk_tilda_jobs_status")),
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_status_status_code"),
        "tilda_jobs_status",
        ["status_code"],
        unique=True,
        schema="integration_tilda",
    )
    op.create_table(
        "tilda_jobs",
        sa.Column("tilda_jobs_id", sa.Integer(), nullable=False),
        sa.Column("tran_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("form_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tilda_jobs_status_id", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("stored_file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date_create", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("date_update", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tilda_jobs_status_id"],
            ["integration_tilda.tilda_jobs_status.tilda_jobs_status_id"],
            name=op.f("fk_tilda_jobs_tilda_jobs_status_id_tilda_jobs_status"),
        ),
        sa.PrimaryKeyConstraint("tilda_jobs_id", name=op.f("pk_tilda_jobs")),
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_form_id"),
        "tilda_jobs",
        ["form_id"],
        unique=False,
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_locked_by"),
        "tilda_jobs",
        ["locked_by"],
        unique=False,
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_locked_until"),
        "tilda_jobs",
        ["locked_until"],
        unique=False,
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_next_retry_at"),
        "tilda_jobs",
        ["next_retry_at"],
        unique=False,
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_tilda_jobs_status_id"),
        "tilda_jobs",
        ["tilda_jobs_status_id"],
        unique=False,
        schema="integration_tilda",
    )
    op.create_index(
        op.f("ix_integration_tilda_tilda_jobs_tran_id"),
        "tilda_jobs",
        ["tran_id"],
        unique=True,
        schema="integration_tilda",
    )
    op.create_table(
        "tilda_jobs_status_history",
        sa.Column("tilda_jobs_status_history_id", sa.Integer(), nullable=False),
        sa.Column("tilda_jobs_id", sa.Integer(), nullable=False),
        sa.Column("tilda_jobs_status_id", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("date_create", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tilda_jobs_id"],
            ["integration_tilda.tilda_jobs.tilda_jobs_id"],
            name=op.f("fk_tilda_jobs_status_history_tilda_jobs_id_tilda_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["tilda_jobs_status_id"],
            ["integration_tilda.tilda_jobs_status.tilda_jobs_status_id"],
            name=op.f("fk_tilda_jobs_status_history_tilda_jobs_status_id_tilda_jobs_status"),
        ),
        sa.PrimaryKeyConstraint("tilda_jobs_status_history_id", name=op.f("pk_tilda_jobs_status_history")),
        schema="integration_tilda",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tilda_jobs_status_history", schema="integration_tilda")
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_tran_id"), table_name="tilda_jobs", schema="integration_tilda"
    )
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_tilda_jobs_status_id"),
        table_name="tilda_jobs",
        schema="integration_tilda",
    )
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_next_retry_at"),
        table_name="tilda_jobs",
        schema="integration_tilda",
    )
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_locked_until"),
        table_name="tilda_jobs",
        schema="integration_tilda",
    )
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_locked_by"), table_name="tilda_jobs", schema="integration_tilda"
    )
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_form_id"), table_name="tilda_jobs", schema="integration_tilda"
    )
    op.drop_table("tilda_jobs", schema="integration_tilda")
    op.drop_index(
        op.f("ix_integration_tilda_tilda_jobs_status_status_code"),
        table_name="tilda_jobs_status",
        schema="integration_tilda",
    )
    op.drop_table("tilda_jobs_status", schema="integration_tilda")
    # ### end Alembic commands ###
