"""add column

Revision ID: 4af782aa7c33
Revises: 7980139eea9c
Create Date: 2026-04-21 19:33:51.710760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af782aa7c33'
down_revision: Union[str, None] = '7980139eea9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilda_job', sa.Column('tran_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tilda_job', sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tilda_job', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tilda_job', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tilda_job', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tilda_job', sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tilda_job', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tilda_job', sa.Column('last_error_message', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_tilda_job_webhook_event_id'), table_name='tilda_job')
    op.create_index(op.f('ix_tilda_job_form_id'), 'tilda_job', ['form_id'], unique=False)
    op.create_index(op.f('ix_tilda_job_locked_by'), 'tilda_job', ['locked_by'], unique=False)
    op.create_index(op.f('ix_tilda_job_locked_until'), 'tilda_job', ['locked_until'], unique=False)
    op.create_index(op.f('ix_tilda_job_next_retry_at'), 'tilda_job', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_tilda_job_tran_id'), 'tilda_job', ['tran_id'], unique=True)
    op.drop_column('tilda_job', 'payload_json')
    op.drop_column('tilda_job', 'webhook_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilda_job', sa.Column('webhook_event_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tilda_job', sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tilda_job_tran_id'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_next_retry_at'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_locked_until'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_locked_by'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_form_id'), table_name='tilda_job')
    op.create_index(op.f('ix_tilda_job_webhook_event_id'), 'tilda_job', ['webhook_event_id'], unique=True)
    op.drop_column('tilda_job', 'last_error_message')
    op.drop_column('tilda_job', 'locked_until')
    op.drop_column('tilda_job', 'locked_by')
    op.drop_column('tilda_job', 'next_retry_at')
    op.drop_column('tilda_job', 'file_url')
    op.drop_column('tilda_job', 'payload')
    op.drop_column('tilda_job', 'form_id')
    op.drop_column('tilda_job', 'tran_id')
    # ### end Alembic commands ###
