"""init tilda tables

Revision ID: 50ea8b8cb364
Revises:
Create Date: 2026-04-20 09:24:19.698394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ea8b8cb364'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tilda_job_status',
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tilda_job_status_id', name=op.f('pk_tilda_job_status'))
    )
    op.create_index(op.f('ix_tilda_job_status_status_code'), 'tilda_job_status', ['status_code'], unique=True)
    op.create_table('tilda_job',
    sa.Column('tilda_job_id', sa.Integer(), nullable=False),
    sa.Column('webhook_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tilda_job_status_id'], ['tilda_job_status.tilda_job_status_id'], name=op.f('fk_tilda_job_tilda_job_status_id_tilda_job_status')),
    sa.PrimaryKeyConstraint('tilda_job_id', name=op.f('pk_tilda_job'))
    )
    op.create_index(op.f('ix_tilda_job_tilda_job_status_id'), 'tilda_job', ['tilda_job_status_id'], unique=False)
    op.create_index(op.f('ix_tilda_job_webhook_event_id'), 'tilda_job', ['webhook_event_id'], unique=True)
    op.create_table('tilda_job_status_history',
    sa.Column('tilda_job_status_history_id', sa.Integer(), nullable=False),
    sa.Column('tilda_job_id', sa.Integer(), nullable=False),
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tilda_job_id'], ['tilda_job.tilda_job_id'], name=op.f('fk_tilda_job_status_history_tilda_job_id_tilda_job')),
    sa.ForeignKeyConstraint(['tilda_job_status_id'], ['tilda_job_status.tilda_job_status_id'], name=op.f('fk_tilda_job_status_history_tilda_job_status_id_tilda_job_status')),
    sa.PrimaryKeyConstraint('tilda_job_status_history_id', name=op.f('pk_tilda_job_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tilda_job_status_history')
    op.drop_index(op.f('ix_tilda_job_webhook_event_id'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_tilda_job_status_id'), table_name='tilda_job')
    op.drop_table('tilda_job')
    op.drop_index(op.f('ix_tilda_job_status_status_code'), table_name='tilda_job_status')
    op.drop_table('tilda_job_status')
    # ### end Alembic commands ###