"""add data

Revision ID: 7980139eea9c
Revises: 50ea8b8cb364
Create Date: 2026-04-20 12:03:29.397320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7980139eea9c'
down_revision: Union[str, None] = '50ea8b8cb364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            INSERT INTO tilda_job_status (tilda_job_status_id, status_code) VALUES
                (1, 'queued'),
                (2, 'processing'),
                (3, 'done'),
                (4, 'failed')
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DELETE FROM tilda_job_status
            WHERE tilda_job_status_id IN (1, 2, 3, 4)
            """
        )
    )
    # ### end Alembic commands ###
