"""init

Revision ID: 7de261471407
Revises: 
Create Date: 2026-04-22 07:08:07.395836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7de261471407'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tilda_job_status',
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tilda_job_status_id', name=op.f('pk_tilda_job_status'))
    )
    op.create_index(op.f('ix_tilda_job_status_status_code'), 'tilda_job_status', ['status_code'], unique=True)
    op.create_table('tilda_job',
    sa.Column('tilda_job_id', sa.Integer(), nullable=False),
    sa.Column('tran_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tilda_job_status_id'], ['tilda_job_status.tilda_job_status_id'], name=op.f('fk_tilda_job_tilda_job_status_id_tilda_job_status')),
    sa.PrimaryKeyConstraint('tilda_job_id', name=op.f('pk_tilda_job'))
    )
    op.create_index(op.f('ix_tilda_job_form_id'), 'tilda_job', ['form_id'], unique=False)
    op.create_index(op.f('ix_tilda_job_locked_by'), 'tilda_job', ['locked_by'], unique=False)
    op.create_index(op.f('ix_tilda_job_locked_until'), 'tilda_job', ['locked_until'], unique=False)
    op.create_index(op.f('ix_tilda_job_next_retry_at'), 'tilda_job', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_tilda_job_tilda_job_status_id'), 'tilda_job', ['tilda_job_status_id'], unique=False)
    op.create_index(op.f('ix_tilda_job_tran_id'), 'tilda_job', ['tran_id'], unique=True)
    op.create_table('tilda_job_status_history',
    sa.Column('tilda_job_status_history_id', sa.Integer(), nullable=False),
    sa.Column('tilda_job_id', sa.Integer(), nullable=False),
    sa.Column('tilda_job_status_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tilda_job_id'], ['tilda_job.tilda_job_id'], name=op.f('fk_tilda_job_status_history_tilda_job_id_tilda_job')),
    sa.ForeignKeyConstraint(['tilda_job_status_id'], ['tilda_job_status.tilda_job_status_id'], name=op.f('fk_tilda_job_status_history_tilda_job_status_id_tilda_job_status')),
    sa.PrimaryKeyConstraint('tilda_job_status_history_id', name=op.f('pk_tilda_job_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tilda_job_status_history')
    op.drop_index(op.f('ix_tilda_job_tran_id'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_tilda_job_status_id'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_next_retry_at'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_locked_until'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_locked_by'), table_name='tilda_job')
    op.drop_index(op.f('ix_tilda_job_form_id'), table_name='tilda_job')
    op.drop_table('tilda_job')
    op.drop_index(op.f('ix_tilda_job_status_status_code'), table_name='tilda_job_status')
    op.drop_table('tilda_job_status')
    # ### end Alembic commands ###
